apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: mdaabidh14/flask-devops-demo:8b4cc36db1df7558d6c94860ef8dd5b78e5215d6
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v1.0"