apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: mdaabidh14/flask-devops-demo:cb6bde134179c8264cf224b3f7187b764ec5d907
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v1.0"