apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: mdaabidh14/flask-devops-demo:e7ce5341a557f11ee952aec5c345e4c95599a5ec
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v1.0"